### PR TITLE
added right click dragging and internal to public

### PR DESCRIPTION
**Pull request by BossSloth**
- added right click dragging for the camera
- serializers are now public so they can be used by other mods

### CODE REVIEW

**Comment by olavim** [comment]
Thanks for the PR! The idea is good. Could you bind camera dragging to middle mouse button instead though? I want to reserve right click to a context menu, in case I decide to add one at some point. Also some way to re-center the camera would be nice.

**Comment by BossSloth** [comment]
@olavim how would i create a button for recentering? I don't see how.

**Comment by pdcook** [comment]
> @olavim how would i create a button for recentering? I don't see how.

Are you asking how to add a keybind? Or how to choose where to recenter the camera?

**Comment by BossSloth** [comment]
i was thinking of a visual button like the play button, but i believe i can't create that because it is in the assetbundle

**Comment by pdcook** [comment]
> i was thinking of a visual button like the play button, but i believe i can't create that because it is in the assetbundle

maybe you could find the gameobject by path and add it from there? just thinking about how I made the 8+ player menu. I'll see if I can get anything real quick

**Comment by pdcook** [comment]
@tddebart Yah, you could try finding any of these objects, cloning them, and Frankensteining them to your liking - for instance by removing/readding the `Button` component and adding a listener that does what you want it to do.

Is it an elegant solution? Absolutely not. But you could do it without access to the assets.

image

**Comment by olavim** [comment]
Any keybind will do for now. I'll do some polishing later.

**Comment by BossSloth** [comment]
alright I will just create a keybind, gonna do that tomorrow

**Comment by BossSloth** [comment]
alright i added a key bind for resetting. You can merge it if you want

**Pull request merged**
